version: "3.9"
services:
    pingservice:
        
        build: 
            context: .
            dockerfile: ./pingservice/Dockerfile-ping
        ports:
            - 8080:8080            
    receiverservice:
        
        build: 
            context: .
            dockerfile: ./receiverservice/Dockerfile-receiver
        ports:
            - 8081:8080            